version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8

 
    steps:
      - add_ssh_keys:
          fingerprints:
            - 12:f8:7e:78:61:b4:bf:e2:de:24:15:96:4e:d4:72:53

      - checkout
      - run: pip install -r requirements.txt
      - run: lektor build && lektor deploy


workflows:
  sample: 
    jobs:
      - build-and-test
